# GLOBAL SITE SETTINGS

# General
seo_title: "Andersons Solicitors – Adelaide Lawyers – South Australia Law Firm"
title: "Andersons Solicitors"
company: "Andersons Solicitors"
description: "South Australian law firm for personal injury compensation, motor vehicle accidents, WorkCover, medical negligence, Family Law, Wills, Criminal Law, Commercial Law located in Adelaide, Port Adelaide, Morphett Vale, Victor Harbor, Murray Bridge, Mt Gambier'"

# Contact Info
email: enquiry@andersons.com.au
phone: (08) 8238 6666
fax: (08) 8238 6604
address: "69 Franklin Street<br>Adelaide<br>South Australia 5000"

# Social Networks
facebook: "https://www.facebook.com/andersonssolicitors"

# Google Map
google_map: ""

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"